#!/bin/sh
#
# creates a todo list via TODO comments

grep -rnE --exclude=todo.txt '[#/] ?TODO' | sed 's/  //g' | sed 's/$/&\n/' > todo.txt

# bundle the client into an archive for easy download
tar -cf shexter_client.tar --exclude-vcs-ignores shexter_client/
gzip -f shexter_client.tar

echo
touch .commit
exit
