#!/bin/sh
#
# creates a todo list via TODO comments

grep -rnE --exclude=todo.txt '[#/] ?TODO' | sed 's/  //g' | sed 's/$/&\n/' > todo.txt

if [ -f shexter_client.tar ]; then
	rm shexter_client.tar
fi
tar -cvf shexter_client.tar shexter_client/
gzip shexter_client.tar

echo
touch .commit
exit
